# Generated by Django 2.1.7 on 2019-07-22 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(upload_to='passports/')),
                ('full_name_of_pupil', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('date_of_birth', models.DateField()),
                ('class_applying_to', models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=128)),
                ('full_name_of_guardian', models.CharField(max_length=50)),
                ('relationship_with_pupil', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=128)),
                ('profession', models.CharField(max_length=50)),
                ('residential_address', models.CharField(max_length=50)),
                ('office_address', models.CharField(max_length=50)),
                ('telephone_1', models.CharField(max_length=50)),
                ('telephone_2', models.CharField(max_length=50)),
                ('child_aliments', models.TextField(help_text='Does the child have any persistent aliments?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
