# Generated by Django 2.2.3 on 2019-07-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190723_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='telephone_1',
            new_name='telephone',
        ),
    ]
