# Generated by Django 2.1.7 on 2019-07-24 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20190723_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, help_text='Enter email address', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='child_aliments',
            field=models.TextField(blank=True, help_text='Does the child have any persistent aliments?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='class_applying_to',
            field=models.CharField(blank=True, choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='firstname_of_pupil',
            field=models.CharField(help_text='Enter firstname of pupil', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='office_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='othername_of_pupil',
            field=models.CharField(blank=True, help_text='Enter othername of pupil', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='residential_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='surname_of_pupil',
            field=models.CharField(help_text='Enter surname of pupil', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
