# Generated by Django 2.1.7 on 2019-07-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20190724_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
