# Generated by Django 2.1.7 on 2019-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_application_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='school_fees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
